### ISSUE TITLE
cannot import name 'read_yuv' from 'siti_tools.file'

### ISSUE THREAD

**Issue by rakeshraor** [slhck/siti#10]
Hi,

I tried using the tool and ran into the following issue

```
Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/tljh/user/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rakesh/work/siti/siti/__main__.py", line 22, in <module>
    from siti_tools.file import read_container, read_yuv, FileFormat
ImportError: cannot import name 'read_yuv' from 'siti_tools.file' (/home/rakesh/.local/lib/python3.9/site-packages/siti_tools/file.py)

```

Could you please let me know if there's a way to get around this?

Thanks,
Rakesh

**Comment by stg7** [comment]
I can confirm this bug

**Comment by slhck** [comment]
Ah, this has to do with the new siti_tools release. It does not have this function. I pinned the dependencies in requirements.txt, but something went wrong apparently.

I removed the dependency and made a [new version](https://pypi.org/project/siti/1.4.5/). Please upgrade:

```
pip3 install --upgrade siti
```

**Comment by rakeshraor** [comment]
Thank you!
